"""add server defaults to status and priority

Revision ID: 06e4e9ac287e
Revises: fa0d215b50a1
Create Date: 2026-09-07 06:49:38.122301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e4e9ac287e'
down_revision: Union[str, Sequence[str], None] = 'fa0d215b50a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(),
               server_default='open',
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               server_default='medium',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
